server:
  port: 9012

spring:
  application:
    name: vecher-web
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka/
  instance:
    prefer-ip-address: true
zuul:
  routes:
    vecher-gathering: # 活动
      path: /gathering/**   # 配置请求URL的请求规则
      serviceId: vecher-gathering  # 指定Eureka注册中心的服务id

    vecher-article: # 文章
      path: /article/**   # 配置请求URL的请求规则
      serviceId: vecher-article  # 指定Eureka注册中心的服务id

    vecher-base: # 基础
      path: /base/**   # 配置请求URL的请求规则
      serviceId: vecher-base  # 指定Eureka注册中心的服务id

    vecher-friend: # 交友
      path: /friend/**   # 配置请求URL的请求规则
      serviceId: vecher-friend  # 指定Eureka注册中心的服务id

    vecher-qa: # 问答
      path: /qa/**   # 配置请求URL的请求规则
      serviceId: vecher-qa  # 指定Eureka注册中心的服务id
    vecher-recruit: # 招聘
      path: /recruit/**   # 配置请求URL的请求规则
      serviceId: vecher-recruit  # 指定Eureka注册中心的服务id

    vecher-spit: # 吐槽
      path: /spit/**   # 配置请求URL的请求规则
      serviceId: vecher-spit  # 指定Eureka注册中心的服务id

    vecher-user: # 用户
      path: /user/**   # 配置请求URL的请求规则
      serviceId: vecher-user  # 指定Eureka注册中心的服务id

    vecher-search: # 搜索
      path: /search/**
      serviceId: vecher-search